apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
spec:
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
        - name: pythonapp
          image: chorochev/simple-python-app-service:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: pythonapp-service
spec:
  type: LoadBalancer
  selector:
    app: pythonapp # Label pods
  ports:
    - name: pythonapp-listener
      protocol: TCP
      port: 80 # The port on the Load Balancer
      targetPort: 5000 # The port on pods
