apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp # Label pods
    spec:
      containers:
        - name: webapp
          image: httpd:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  selector:
    app: webapp # Label pods
  ports:
    - name: webapp-listener
      protocol: TCP
      port: 80 # The port on the Load Balancer
      targetPort: 80 # The port on pods
