apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings
spec:
  selector:
    matchLabels:
      app: greetings
  template:
    metadata:
      labels:
        app: greetings
    spec:
      nodeSelector:
        tier: frontend
      containers:
        - name: greetings
          image: chorochev/greetings:latest
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: my-volume-name
              mountPath: /app/config.conf
              subPath: config.conf
      volumes:
        - name: my-volume-name
          configMap:
            name: my-configmap-name          

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: greetings
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: greetings
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50

---
apiVersion: v1
kind: Service
metadata:
  name: greetings
spec:
  type: LoadBalancer
  selector:
    app: greetings # Label deployment
  ports:
    - name: greetings-listener
      protocol: TCP
      port: 80 # The port on the Load Balancer
      targetPort: 5000 # The port on pods

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        tier: frontend
      containers:
        - name: redis
          image: redis:latest
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 6379

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: redis
# spec:
#   type: ClusterIP
#   selector:
#     app: redis # Label deployment
#   ports:
#     - name: redis-listener
#       protocol: TCP
#       port: 6379 # The port on the Load Balancer
#       targetPort: 6379 # The port on pods

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis

--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap-name
  namespace: default
data:
  config.conf: |
    Aleksei Khoroshev
