apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  labels:
    env: test
spec:
  containers:
    - name: nginx
      image: nginx:latest
      resources:
        limits:
          memory: "100Mi"
          cpu: "100m"
      ports:
        - containerPort: 80
  nodeSelector:
    tier: frontend
