apiVersion: v1
kind: Pod
metadata:
  name: pod-pythonapp
  labels:
    env: test
spec:
  containers:
    - name: pythonapp
      image: chorochev/simple-python-app-service:latest
      resources:
        limits:
          memory: "100Mi"
          cpu: "100m"
      ports:
        - containerPort: 5000
  nodeSelector:
    tier: frontend
