apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    env: test
spec:
  containers:
    - name: redis
      image: redis:latest
      resources:
        limits:
          memory: "100Mi"
          cpu: "100m"
      ports:
        - containerPort: 6379
  nodeSelector:
    tier: frontend
