apiVersion: v1
kind: Pod
metadata:
  name: epamlab-greetings
  labels:
    env: test
spec:
  containers:
    - name: epamlab-greetings
      image: epamlab-greetings:latest
      resources:
        limits:
          memory: "100Mi"
          cpu: "100m"
      ports:
        - containerPort: 5000
  nodeSelector:
    tier: frontend
